import type { Lead, LeadScore } from "./types"

export const mockLeads: Lead[] = [
  {
    id: "1",
    name: "John Smith",
    email: "john.smith@techcorp.com",
    company: "TechCorp Inc",
    phone: "+1-555-0101",
    source: "Website",
    status: "qualified",
    score: 85,
    createdAt: new Date("2025-01-15"),
    lastContactedAt: new Date("2025-01-20"),
    dealValue: 50000,
    industry: "Technology",
    employeeCount: 250,
    website: "https://techcorp.com",
  },
  {
    id: "2",
    name: "Sarah Johnson",
    email: "sarah.j@innovate.io",
    company: "Innovate Solutions",
    phone: "+1-555-0102",
    source: "LinkedIn",
    status: "contacted",
    score: 72,
    createdAt: new Date("2025-01-18"),
    lastContactedAt: new Date("2025-01-22"),
    dealValue: 35000,
    industry: "Software",
    employeeCount: 150,
    website: "https://innovate.io",
  },
  {
    id: "3",
    name: "Michael Chen",
    email: "mchen@dataflow.com",
    company: "DataFlow Analytics",
    phone: "+1-555-0103",
    source: "Referral",
    status: "new",
    score: 91,
    createdAt: new Date("2025-01-25"),
    dealValue: 75000,
    industry: "Data Analytics",
    employeeCount: 500,
    website: "https://dataflow.com",
  },
  {
    id: "4",
    name: "Emily Rodriguez",
    email: "emily.r@cloudnine.com",
    company: "CloudNine Systems",
    phone: "+1-555-0104",
    source: "Conference",
    status: "qualified",
    score: 78,
    createdAt: new Date("2025-01-20"),
    lastContactedAt: new Date("2025-01-28"),
    dealValue: 45000,
    industry: "Cloud Services",
    employeeCount: 300,
    website: "https://cloudnine.com",
  },
  {
    id: "5",
    name: "David Park",
    email: "dpark@fintech.co",
    company: "FinTech Solutions",
    phone: "+1-555-0105",
    source: "Email Campaign",
    status: "converted",
    score: 88,
    createdAt: new Date("2025-01-10"),
    lastContactedAt: new Date("2025-01-30"),
    dealValue: 60000,
    industry: "Finance",
    employeeCount: 400,
    website: "https://fintech.co",
  },
  {
    id: "6",
    name: "Lisa Anderson",
    email: "l.anderson@retail.com",
    company: "Retail Plus",
    phone: "+1-555-0106",
    source: "Website",
    status: "new",
    score: 45,
    createdAt: new Date("2025-01-28"),
    dealValue: 15000,
    industry: "Retail",
    employeeCount: 50,
    website: "https://retailplus.com",
  },
  {
    id: "7",
    name: "Robert Taylor",
    email: "rtaylor@manufacturing.com",
    company: "Manufacturing Pro",
    phone: "+1-555-0107",
    source: "Trade Show",
    status: "contacted",
    score: 68,
    createdAt: new Date("2025-01-22"),
    lastContactedAt: new Date("2025-01-29"),
    dealValue: 40000,
    industry: "Manufacturing",
    employeeCount: 200,
    website: "https://manufacturing.com",
  },
  {
    id: "8",
    name: "Jennifer Lee",
    email: "jlee@healthtech.io",
    company: "HealthTech Innovations",
    phone: "+1-555-0108",
    source: "LinkedIn",
    status: "qualified",
    score: 82,
    createdAt: new Date("2025-01-16"),
    lastContactedAt: new Date("2025-01-26"),
    dealValue: 55000,
    industry: "Healthcare",
    employeeCount: 350,
    website: "https://healthtech.io",
  },
  {
    id: "9",
    name: "Alex Martinez",
    email: "alex.m@startup.io",
    company: "Startup Ventures",
    phone: "+1-555-0109",
    source: "Website",
    status: "qualified",
    score: 79,
    createdAt: new Date("2025-01-19"),
    lastContactedAt: new Date("2025-01-27"),
    dealValue: 42000,
    industry: "Technology",
    employeeCount: 80,
    website: "https://startup.io",
  },
  {
    id: "10",
    name: "Rachel Green",
    email: "rgreen@enterprise.com",
    company: "Enterprise Corp",
    phone: "+1-555-0110",
    source: "Referral",
    status: "converted",
    score: 94,
    createdAt: new Date("2025-01-12"),
    lastContactedAt: new Date("2025-02-01"),
    dealValue: 120000,
    industry: "Enterprise Software",
    employeeCount: 1000,
    website: "https://enterprise.com",
  },
  {
    id: "11",
    name: "Tom Wilson",
    email: "twilson@consulting.com",
    company: "Wilson Consulting",
    phone: "+1-555-0111",
    source: "LinkedIn",
    status: "contacted",
    score: 65,
    createdAt: new Date("2025-01-24"),
    lastContactedAt: new Date("2025-01-31"),
    dealValue: 28000,
    industry: "Consulting",
    employeeCount: 120,
    website: "https://consulting.com",
  },
  {
    id: "12",
    name: "Maria Garcia",
    email: "mgarcia@ecommerce.com",
    company: "E-Commerce Plus",
    phone: "+1-555-0112",
    source: "Email Campaign",
    status: "new",
    score: 58,
    createdAt: new Date("2025-01-29"),
    dealValue: 22000,
    industry: "E-Commerce",
    employeeCount: 90,
    website: "https://ecommerce.com",
  },
  {
    id: "13",
    name: "James Brown",
    email: "jbrown@logistics.com",
    company: "Global Logistics",
    phone: "+1-555-0113",
    source: "Conference",
    status: "qualified",
    score: 81,
    createdAt: new Date("2025-01-17"),
    lastContactedAt: new Date("2025-01-25"),
    dealValue: 65000,
    industry: "Logistics",
    employeeCount: 450,
    website: "https://logistics.com",
  },
  {
    id: "14",
    name: "Nina Patel",
    email: "npatel@biotech.com",
    company: "BioTech Research",
    phone: "+1-555-0114",
    source: "Referral",
    status: "contacted",
    score: 76,
    createdAt: new Date("2025-01-21"),
    lastContactedAt: new Date("2025-01-28"),
    dealValue: 48000,
    industry: "Biotechnology",
    employeeCount: 280,
    website: "https://biotech.com",
  },
  {
    id: "15",
    name: "Chris Evans",
    email: "cevans@media.com",
    company: "Digital Media Co",
    phone: "+1-555-0115",
    source: "Trade Show",
    status: "new",
    score: 52,
    createdAt: new Date("2025-01-26"),
    dealValue: 18000,
    industry: "Media",
    employeeCount: 65,
    website: "https://media.com",
  },
  {
    id: "16",
    name: "Sophie Turner",
    email: "sturner@saas.io",
    company: "SaaS Innovations",
    phone: "+1-555-0116",
    source: "Website",
    status: "qualified",
    score: 87,
    createdAt: new Date("2025-01-14"),
    lastContactedAt: new Date("2025-01-23"),
    dealValue: 72000,
    industry: "SaaS",
    employeeCount: 320,
    website: "https://saas.io",
  },
  {
    id: "17",
    name: "Daniel Kim",
    email: "dkim@automotive.com",
    company: "Auto Tech Systems",
    phone: "+1-555-0117",
    source: "LinkedIn",
    status: "converted",
    score: 89,
    createdAt: new Date("2025-01-11"),
    lastContactedAt: new Date("2025-01-29"),
    dealValue: 85000,
    industry: "Automotive",
    employeeCount: 550,
    website: "https://automotive.com",
  },
  {
    id: "18",
    name: "Olivia White",
    email: "owhite@education.edu",
    company: "EduTech Platform",
    phone: "+1-555-0118",
    source: "Email Campaign",
    status: "contacted",
    score: 70,
    createdAt: new Date("2025-01-23"),
    lastContactedAt: new Date("2025-01-30"),
    dealValue: 38000,
    industry: "Education",
    employeeCount: 180,
    website: "https://education.edu",
  },
]

export const mockLeadScores: LeadScore[] = mockLeads.map((lead) => ({
  leadId: lead.id,
  score: lead.score || 0,
  confidence: 0.85 + Math.random() * 0.1,
  factors: {
    engagement: Math.random() * 100,
    companySize: (lead.employeeCount || 0) / 10,
    industry: Math.random() * 100,
    dealValue: (lead.dealValue || 0) / 1000,
    responseTime: Math.random() * 100,
  },
  prediction: lead.score! > 80 ? "high" : lead.score! > 60 ? "medium" : "low",
  recommendations: [
    "Schedule a demo call within 48 hours",
    "Send personalized product information",
    "Connect on LinkedIn",
  ],
  calculatedAt: new Date(),
}))
